name: 'Books & Conversations'
description: Thought-provoking books and engaging conversation.
destination: public
exclude: ['CNAME', 'config.ru']
permalink: /:title
url: http://booksandconversations.com
twitter: booksconvos
facebook: booksandconversations