name: 'Books & Conversations'
defaults:
  -
    scope:
      path: '_posts'
      type: post
    values:
      type: post
description: Engaging conversations about thought-provoking books.
destination: public
exclude: ['CNAME', 'config.ru', 'sass']
sass:
  sass_dir: sass
  style: :compressed
permalink: /:title
url: http://booksandconversations.com
facebook: booksandconversations
facebook_url: https://www.facebook.com/booksandconversations
feedburner_url: http://feeds.smallepic.com/booksandconversations
google_analytics: UA-39582779-3
twitter: '@booksconvos'
twitter_url: https://twitter.com/booksconvos
