name: 'Books & Conversations'
description: Engaging conversations about thought-provoking books.
destination: public
exclude: ['CNAME', 'config.ru']
permalink: /:title
url: http://booksandconversations.com
twitter: booksconvos
facebook: booksandconversations
google_analytics: UA-39582779-3